SprintApp.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SprintApp.Core.Models;
using System.Diagnostics;

namespace SprintApp.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SprintApp.UI/Controllers/ProjectManagerController.cs
using Microsoft.AspNetCore.Mvc;
using SprintApp.Core.Dtos;
using SprintApp.Core.Helper;
using SprintApp.Core.IServices;
using SprintApp.Core.Models;
#nullable disable

namespace SprintApp.UI.Controllers
{
    public class ProjectManagerController : Controller
    {
        private readonly IProjectManagerService _service;

        public ProjectManagerController(IProjectManagerService service)
        {
            _service = service;
        }

        public async Task<ActionResult<ProjectManager>> ProjectManagerLandingPage(string email)
        {
            
            var result = await _service.GetProjectManagerAsync(email);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        [HttpGet]
        public IActionResult ProjectManagerLandingPage(ProjectManager obj)
        {
            
            return View(obj);
        }

        public IActionResult Register()
        {
            return View();
        }

        //Post
        [HttpPost]
        public async Task<IActionResult> Register(RegistrationDto dto)
        {
            var result = await _service.RegisterManager(dto);
            if(result == ConstantMessage.Unsuccessful)
            {
                return BadRequest(result);
            }
            return RedirectToAction("Login");
        }

        public IActionResult Login()
        {
            return View();
        }

        //Post
        //[HttpPost]
        //public async Task<ActionResult<LoginDto>> Login(LoginDto dto)
        //{
        //    var result = await _service.Login(dto);
        //    if (result.LogoutTime > DateTime.UtcNow && result.LogoutTime != null)
        //    {
        //        return BadRequest(ConstantMessage.LockedUser);
        //    }
        //    if (result.VerifiedAt == null)
        //    {
        //        return View("Verify");
        //    }
        //    return RedirectToAction("ProjectManagerLandingPage");
        //}

        public IActionResult Verify()
        {
            return View();
        }

        //Post
        [HttpPost]
        public async Task<IActionResult> Verify(VerificationDto dto)
        {
            var result = await _service.VerifyUser(dto);
            if( result == ConstantMessage.InvalidToken)
            {
                return RedirectToAction("Verify");
            }
            if (result != ConstantMessage.CompleteRequest)
            {
                return BadRequest(result);
            }
            return RedirectToAction("Login");
        }
    }
}

SprintApp.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3 class="display-3">
        Welcome, Click the button below to register or login
    </h3>
    <div class="w-75 btn-group" role="group">
            <a asp-controller="ProjectManager" asp-action="Register" class="btn btn-primary mx-2">Register</a>
    </div>
    <div class="w-25 btn-group" role="group">
        <a asp-controller="ProjectManager" asp-action="Login" class="btn btn-primary mx-2">Login</a>
    </div>
    
</div>

SprintApp.UI/Views/ProjectManager/Login.cshtml
@using SprintApp.Core.Dtos;
@model LoginDto
@{
    ViewData["Title"] = "Login";
}


<form method="get">
    <div class="border p-3 mt-4">
        <div class="text-center">
            <h2 class="display-3">Login</h2>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="EmailId">Email address</label>
            <input asp-for="EmailId" class="form-control" />
            <span asp-validation-for="EmailId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Password">Password</label>
            <input asp-for="Password" type="password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        <a asp-controller="ProjectManager" asp-action="ProjectManagerLandingPage" type="submit" class="btn btn-primary">Login</a>
    </div>
</form>
@* <div>
    <a asp-action="ProjectManagerLandingPage" asp-route-id="@Model.EmailId"></a>
</div> *@

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

SprintApp.UI/Views/ProjectManager/ProjectManagerLandingPage.cshtml
@using SprintApp.Core.Dtos;
@using SprintApp.Core.Models;
@model ProjectManager
@{
    ViewData["Title"] = "ProjectManagerLandingPage";
}
<table method="post" asp-action="ProjectManagerLandingPage"></table>
<h1>Welcome @Model.FirstName, @Model.LastName </h1>

@foreach(var item in Model.UserStories)
{
    var userStrory = new UserStoryDto
    {
        Title = item.Title,
        Description = item.Description,
        SprintId = item.SprintId
    };
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    Descripion
                </th>
                <th>
                    Id
                </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td width="30%">
                    @userStrory.Title
                </td>
                <td width="30%">
                    @userStrory.Description
                </td>
                <td width="30%">
                    @userStrory.SprintId
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="ProjectManager" asp-action="ProjectManagerLandingPage" asp-route-Id="@Model.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i></a>
                    </div>
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="ProjectManager" asp-action="ProjectManagerLandingPage" asp-route-Id="@Model.Id" class="btn btn-primary mx-2 btn-danger"><i class="bi bi-trash3"></i></a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
};

SprintApp.UI/Views/ProjectManager/Register.cshtml
@using SprintApp.Core.Dtos;
@model RegistrationDto
@{
    ViewData["Title"] = "Register";
}


<form method="post">
    <div class="border p-3 mt-4">
        <div class="text-center">
            <h class="display-3">Register here</h>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="FirstName">First Name</label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="LastName">Last Name</label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="EmailId">Email address</label>
            <input asp-for="EmailId" class="form-control" />
            <span asp-validation-for="EmailId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Password">Password</label>
            <input asp-for="Password" type="password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

SprintApp.UI/Views/ProjectManager/Verify.cshtml
@using SprintApp.Core.Dtos;
@model VerificationDto
@{
    ViewData["Title"] = "Verify";
}


<form method="post">
    <div class="border p-3 mt-4">
        <div class="text-center">
            <h2 class="display-3">Verify User</h2>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="EmailId">Email address</label>
            <input asp-for="EmailId" class="form-control" />
            <span asp-validation-for="EmailId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="VerificationToken">Token</label>
            <input asp-for="VerificationToken" type="password" class="form-control" />
            <span asp-validation-for="VerificationToken" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Verify</button>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

SprintApp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SprintApp.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Theme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SprintApp.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>       
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sprint Master</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Muhydeen Adediran - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>